/// Groth16 PoC: Verify a snarkjs-generated proof on Sui
/// Circuit: multiplier (a * b = c, c is public output)
module suicryptolib::groth16_poc {
    use sui::groth16;

    /// Verify a Groth16 proof using prepare_verifying_key
    /// vk_bytes: full verifying key in Arkworks compressed format
    /// proof_bytes: A(G1) || B(G2) || C(G1) = 128 bytes
    /// public_inputs_bytes: each scalar as 32 bytes LE
    public fun verify_proof(
        vk_bytes: vector<u8>,
        proof_bytes: vector<u8>,
        public_inputs_bytes: vector<u8>,
    ): bool {
        let curve = groth16::bn254();
        let pvk = groth16::prepare_verifying_key(&curve, &vk_bytes);
        let inputs = groth16::public_proof_inputs_from_bytes(public_inputs_bytes);
        let proof = groth16::proof_points_from_bytes(proof_bytes);

        groth16::verify_groth16_proof(&curve, &pvk, &inputs, &proof)
    }

    #[test]
    fun test_multiplier_proof() {
        // Proof for 3 * 7 = 21 (generated by snarkjs, converted to Arkworks format)
        let vk = x"e2f26dbea299f5223b646cb1fb33eadb059d9407559d7441dfd902e3a79a4d2dabb73dc17fbc13021e2471e0c08bd67d8401f52b73d6d07483794cad4778180e0c06f33bbc4c79a9cadef253a68084d382f17788f885c9afd176f7cb2f036789edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1993d90f8ca4608a929cdafdffda650bada85ba0e5dc420577426f9feea455ae021b196d0f107a709dc219dad5cb68daf2e1bf60cc3b70f47c3c8867a8deade52f02000000000000000d8bec28c135a21ee76b7bc068d2a7f76cfb425f123821a7a497bbd2ecde130ffbdf9b01f88e157fb531c58ce634f3bf74739273710f5d20f470dd3c5f0d89a7";

        let proof = x"1f13eeb5fea7093913e541fbc5b21d292db1bb55645d2fae3d674325b5af1c05b690ffa3d4fc520df95dbc81024782cd148a991913b6305c0874323084bc2208dfea92b1efe3287fa68251ce7fa660e0c66c9cf57af27eeba27bb81f91378c262373deeb096b15611b4dbcf877934a7b57eddda2f336fc6457f661e617591501";

        let public_inputs = x"1500000000000000000000000000000000000000000000000000000000000000";

        assert!(verify_proof(vk, proof, public_inputs), 0);
    }

    #[test]
    fun test_invalid_public_input_fails() {
        let vk = x"e2f26dbea299f5223b646cb1fb33eadb059d9407559d7441dfd902e3a79a4d2dabb73dc17fbc13021e2471e0c08bd67d8401f52b73d6d07483794cad4778180e0c06f33bbc4c79a9cadef253a68084d382f17788f885c9afd176f7cb2f036789edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1993d90f8ca4608a929cdafdffda650bada85ba0e5dc420577426f9feea455ae021b196d0f107a709dc219dad5cb68daf2e1bf60cc3b70f47c3c8867a8deade52f02000000000000000d8bec28c135a21ee76b7bc068d2a7f76cfb425f123821a7a497bbd2ecde130ffbdf9b01f88e157fb531c58ce634f3bf74739273710f5d20f470dd3c5f0d89a7";

        let proof = x"1f13eeb5fea7093913e541fbc5b21d292db1bb55645d2fae3d674325b5af1c05b690ffa3d4fc520df95dbc81024782cd148a991913b6305c0874323084bc2208dfea92b1efe3287fa68251ce7fa660e0c66c9cf57af27eeba27bb81f91378c262373deeb096b15611b4dbcf877934a7b57eddda2f336fc6457f661e617591501";

        // Wrong public input: 22 instead of 21
        let wrong_inputs = x"1600000000000000000000000000000000000000000000000000000000000000";

        assert!(!verify_proof(vk, proof, wrong_inputs), 1);
    }
}
