/// Merkle Proof Verification Library
///
/// Verifies Merkle inclusion proofs using standard hash functions
/// (SHA256, Blake2b-256, Keccak256).
///
/// Uses domain separation to prevent second preimage attacks:
///   leaf hash     = H(0x00 || data)
///   internal node = H(0x01 || left || right)
///
/// Usage:
///   1. Off-chain: build Merkle tree, compute root, generate proof
///   2. On-chain: store root, verify proof when user claims membership
///
/// Proof format:
///   - proof: vector of sibling hashes from leaf to root
///   - positions: for each level, 0 if the current node is on the left, 1 if on the right
module suicryptolib::merkle {
    use std::hash;
    use sui::hash::{blake2b256, keccak256};

    // --- Error codes ---

    /// Hash scheme must be 0 (SHA256), 1 (Blake2b), or 2 (Keccak256)
    const EInvalidScheme: u64 = 0;
    /// Proof and positions vectors must have the same length
    const ELengthMismatch: u64 = 1;
    /// Position value must be 0 (left) or 1 (right)
    const EInvalidPosition: u64 = 2;

    // --- Constants ---

    const SCHEME_SHA256: u8 = 0;
    const SCHEME_BLAKE2B: u8 = 1;
    const SCHEME_KECCAK256: u8 = 2;

    /// Domain separation prefix for leaf nodes
    const LEAF_PREFIX: u8 = 0x00;
    /// Domain separation prefix for internal nodes
    const INTERNAL_PREFIX: u8 = 0x01;

    // --- Public functions ---

    /// Verify a Merkle inclusion proof.
    ///
    /// Arguments:
    /// - root: the known Merkle root
    /// - leaf: the leaf hash (already computed via hash_leaf)
    /// - proof: sibling hashes from leaf to root
    /// - positions: for each level, 0 = current is left child, 1 = current is right child
    /// - scheme: hash function to use (0=SHA256, 1=Blake2b, 2=Keccak256)
    ///
    /// Returns true if the proof is valid.
    public fun verify_proof(
        root: vector<u8>,
        leaf: vector<u8>,
        proof: vector<vector<u8>>,
        positions: vector<u8>,
        scheme: u8,
    ): bool {
        assert!(scheme <= SCHEME_KECCAK256, EInvalidScheme);

        let proof_len = vector::length(&proof);
        let positions_len = vector::length(&positions);
        assert!(proof_len == positions_len, ELengthMismatch);

        let mut current = leaf;
        let mut i = 0;
        while (i < proof_len) {
            let sibling = *vector::borrow(&proof, i);
            let pos = *vector::borrow(&positions, i);
            assert!(pos <= 1, EInvalidPosition);

            current = if (pos == 0) {
                // Current node is left child
                hash_pair_internal(current, sibling, scheme)
            } else {
                // Current node is right child
                hash_pair_internal(sibling, current, scheme)
            };
            i = i + 1;
        };

        current == root
    }

    /// Compute the leaf hash with domain separation prefix.
    /// leaf_hash = H(0x00 || data)
    public fun hash_leaf(data: vector<u8>, scheme: u8): vector<u8> {
        assert!(scheme <= SCHEME_KECCAK256, EInvalidScheme);
        let mut prefixed = vector[LEAF_PREFIX];
        vector::append(&mut prefixed, data);
        hash_with_scheme(prefixed, scheme)
    }

    /// Compute the hash of an internal node with domain separation prefix.
    /// node_hash = H(0x01 || left || right)
    public fun hash_pair(left: vector<u8>, right: vector<u8>, scheme: u8): vector<u8> {
        assert!(scheme <= SCHEME_KECCAK256, EInvalidScheme);
        hash_pair_internal(left, right, scheme)
    }

    // --- Internal functions ---

    /// Internal: compute internal node hash (caller already validated scheme)
    fun hash_pair_internal(left: vector<u8>, right: vector<u8>, scheme: u8): vector<u8> {
        let mut data = vector[INTERNAL_PREFIX];
        vector::append(&mut data, left);
        vector::append(&mut data, right);
        hash_with_scheme(data, scheme)
    }

    /// Hash data with the specified scheme
    fun hash_with_scheme(data: vector<u8>, scheme: u8): vector<u8> {
        if (scheme == SCHEME_SHA256) {
            hash::sha2_256(data)
        } else if (scheme == SCHEME_BLAKE2B) {
            blake2b256(&data)
        } else {
            keccak256(&data)
        }
    }

    // ========== Tests ==========

    // --- Test vectors generated by sdk/test/merkle_reference.mjs ---
    // Tree uses: leaf = SHA256(0x00 || data), node = SHA256(0x01 || left || right)

    #[test]
    fun test_hash_leaf_deterministic() {
        let a = hash_leaf(b"alice", SCHEME_SHA256);
        let b = hash_leaf(b"alice", SCHEME_SHA256);
        assert!(a == b, 0);
    }

    #[test]
    fun test_hash_leaf_different_data() {
        let a = hash_leaf(b"alice", SCHEME_SHA256);
        let b = hash_leaf(b"bob", SCHEME_SHA256);
        assert!(a != b, 0);
    }

    #[test]
    fun test_hash_leaf_different_schemes() {
        let sha = hash_leaf(b"test", SCHEME_SHA256);
        let blake = hash_leaf(b"test", SCHEME_BLAKE2B);
        let keccak = hash_leaf(b"test", SCHEME_KECCAK256);
        assert!(sha != blake, 0);
        assert!(sha != keccak, 1);
        assert!(blake != keccak, 2);
    }

    #[test]
    fun test_hash_leaf_reference_values() {
        // Cross-validated with Node.js: SHA256(0x00 || "alice")
        let leaf0 = hash_leaf(b"alice", SCHEME_SHA256);
        assert!(leaf0 == x"1255dacaa637f70cb606763d3035c7ef6b52eb2983c5cd906f714c3818d0dfaa", 0);

        let leaf1 = hash_leaf(b"bob", SCHEME_SHA256);
        assert!(leaf1 == x"680e7793d646bb7dfa049f6dd432ee3cb38655faa80be01384454efa4bbbb1eb", 1);
    }

    #[test]
    fun test_hash_pair_reference() {
        let leaf0 = x"1255dacaa637f70cb606763d3035c7ef6b52eb2983c5cd906f714c3818d0dfaa";
        let leaf1 = x"680e7793d646bb7dfa049f6dd432ee3cb38655faa80be01384454efa4bbbb1eb";

        // SHA256(0x01 || leaf0 || leaf1)
        let node = hash_pair(leaf0, leaf1, SCHEME_SHA256);
        assert!(node == x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83", 0);
    }

    #[test]
    fun test_hash_pair_order_matters() {
        let a = hash_leaf(b"alice", SCHEME_SHA256);
        let b = hash_leaf(b"bob", SCHEME_SHA256);
        let ab = hash_pair(a, b, SCHEME_SHA256);
        let ba = hash_pair(b, a, SCHEME_SHA256);
        assert!(ab != ba, 0);
    }

    #[test]
    fun test_domain_separation() {
        // Leaf hash and internal hash of the same data should differ
        let data = x"1255dacaa637f70cb606763d3035c7ef6b52eb2983c5cd906f714c3818d0dfaa";
        let as_leaf = hash_leaf(data, SCHEME_SHA256);
        // Internal node of (data, empty) - just to show prefix difference
        let mut internal_data = vector[INTERNAL_PREFIX];
        vector::append(&mut internal_data, data);
        let as_internal = std::hash::sha2_256(internal_data);
        assert!(as_leaf != as_internal, 0);
    }

    // --- 2-leaf tree (depth 1) ---

    #[test]
    fun test_verify_2_leaves_left() {
        let leaf0 = hash_leaf(b"alice", SCHEME_SHA256);
        let leaf1 = hash_leaf(b"bob", SCHEME_SHA256);
        let root = x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83";

        // Proof for leaf0 (left child): sibling = leaf1, position = 0
        let proof = vector[leaf1];
        let positions = vector[0u8];
        assert!(verify_proof(root, leaf0, proof, positions, SCHEME_SHA256), 0);
    }

    #[test]
    fun test_verify_2_leaves_right() {
        let leaf0 = hash_leaf(b"alice", SCHEME_SHA256);
        let leaf1 = hash_leaf(b"bob", SCHEME_SHA256);
        let root = x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83";

        // Proof for leaf1 (right child): sibling = leaf0, position = 1
        let proof = vector[leaf0];
        let positions = vector[1u8];
        assert!(verify_proof(root, leaf1, proof, positions, SCHEME_SHA256), 0);
    }

    // --- 4-leaf tree (depth 2) ---

    #[test]
    fun test_verify_4_leaves_leaf0() {
        let leaf0 = x"1255dacaa637f70cb606763d3035c7ef6b52eb2983c5cd906f714c3818d0dfaa";
        let leaf1 = x"680e7793d646bb7dfa049f6dd432ee3cb38655faa80be01384454efa4bbbb1eb";
        let node23 = x"cce2b29fbe76c4b522233f9e90cbcbc29fd5e4d8233f4abdc576de5fefc923b7";
        let root = x"ebba995839ee5ec0a720998bfefba84675244b9684b9203aade54754bb602ed5";

        // Proof for leaf0: siblings=[leaf1, node23], positions=[0, 0]
        let proof = vector[leaf1, node23];
        let positions = vector[0u8, 0u8];
        assert!(verify_proof(root, leaf0, proof, positions, SCHEME_SHA256), 0);
    }

    #[test]
    fun test_verify_4_leaves_leaf3() {
        let leaf2 = x"f931962f0917c346d447293c07b687ae1609f7003f8a44a06a75c4145b1e1929";
        let leaf3 = x"262bdada8a2e394abb74edde5b72151581231631a2959b611d54c473639a40f9";
        let node01 = x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83";
        let root = x"ebba995839ee5ec0a720998bfefba84675244b9684b9203aade54754bb602ed5";

        // Proof for leaf3: siblings=[leaf2, node01], positions=[1, 1]
        let proof = vector[leaf2, node01];
        let positions = vector[1u8, 1u8];
        assert!(verify_proof(root, leaf3, proof, positions, SCHEME_SHA256), 0);
    }

    #[test]
    fun test_verify_4_leaves_leaf2() {
        let leaf3 = x"262bdada8a2e394abb74edde5b72151581231631a2959b611d54c473639a40f9";
        let node01 = x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83";
        let root = x"ebba995839ee5ec0a720998bfefba84675244b9684b9203aade54754bb602ed5";

        // Proof for leaf2: siblings=[leaf3, node01], positions=[0, 1]
        let proof = vector[leaf3, node01];
        let positions = vector[0u8, 1u8];
        assert!(verify_proof(root, hash_leaf(b"charlie", SCHEME_SHA256), proof, positions, SCHEME_SHA256), 0);
    }

    // --- Invalid proof tests ---

    #[test]
    fun test_verify_wrong_root_fails() {
        let leaf0 = hash_leaf(b"alice", SCHEME_SHA256);
        let leaf1 = hash_leaf(b"bob", SCHEME_SHA256);
        let wrong_root = x"0000000000000000000000000000000000000000000000000000000000000000";

        let proof = vector[leaf1];
        let positions = vector[0u8];
        assert!(!verify_proof(wrong_root, leaf0, proof, positions, SCHEME_SHA256), 0);
    }

    #[test]
    fun test_verify_wrong_leaf_fails() {
        let leaf1 = hash_leaf(b"bob", SCHEME_SHA256);
        let root = x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83";
        let fake_leaf = hash_leaf(b"eve", SCHEME_SHA256);

        let proof = vector[leaf1];
        let positions = vector[0u8];
        // Eve is not in the tree
        assert!(!verify_proof(root, fake_leaf, proof, positions, SCHEME_SHA256), 0);
    }

    #[test]
    fun test_verify_wrong_sibling_fails() {
        let leaf0 = hash_leaf(b"alice", SCHEME_SHA256);
        let root = x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83";
        let wrong_sibling = hash_leaf(b"eve", SCHEME_SHA256);

        let proof = vector[wrong_sibling]; // should be leaf1=hash("bob")
        let positions = vector[0u8];
        assert!(!verify_proof(root, leaf0, proof, positions, SCHEME_SHA256), 0);
    }

    #[test]
    fun test_verify_wrong_position_fails() {
        let leaf0 = hash_leaf(b"alice", SCHEME_SHA256);
        let leaf1 = hash_leaf(b"bob", SCHEME_SHA256);
        let root = x"3bc1199d175a1cfc2c3fe16b1920a93ca6397484cbda581a4b7c6b920f93ba83";

        // leaf0 is at position 0 (left), but we claim position 1 (right)
        let proof = vector[leaf1];
        let positions = vector[1u8]; // wrong!
        assert!(!verify_proof(root, leaf0, proof, positions, SCHEME_SHA256), 0);
    }

    // --- Empty proof (single leaf = root) ---

    #[test]
    fun test_verify_single_leaf() {
        // A tree with a single leaf: the leaf IS the root
        let leaf = hash_leaf(b"only_member", SCHEME_SHA256);
        let proof = vector::empty<vector<u8>>();
        let positions = vector::empty<u8>();
        assert!(verify_proof(leaf, leaf, proof, positions, SCHEME_SHA256), 0);
    }

    // --- Blake2b scheme ---

    #[test]
    fun test_verify_blake2b() {
        let leaf0 = hash_leaf(b"alice", SCHEME_BLAKE2B);
        let leaf1 = hash_leaf(b"bob", SCHEME_BLAKE2B);
        let root = hash_pair(leaf0, leaf1, SCHEME_BLAKE2B);

        let proof = vector[leaf1];
        let positions = vector[0u8];
        assert!(verify_proof(root, leaf0, proof, positions, SCHEME_BLAKE2B), 0);
    }

    // --- Keccak256 scheme ---

    #[test]
    fun test_verify_keccak256() {
        let leaf0 = hash_leaf(b"alice", SCHEME_KECCAK256);
        let leaf1 = hash_leaf(b"bob", SCHEME_KECCAK256);
        let root = hash_pair(leaf0, leaf1, SCHEME_KECCAK256);

        let proof = vector[leaf1];
        let positions = vector[0u8];
        assert!(verify_proof(root, leaf0, proof, positions, SCHEME_KECCAK256), 0);
    }

    // --- Error handling ---

    #[test]
    #[expected_failure(abort_code = EInvalidScheme)]
    fun test_invalid_scheme() {
        hash_leaf(b"test", 3);
    }

    #[test]
    #[expected_failure(abort_code = ELengthMismatch)]
    fun test_length_mismatch() {
        let root = x"0000000000000000000000000000000000000000000000000000000000000000";
        let leaf = x"0000000000000000000000000000000000000000000000000000000000000000";
        let proof = vector[root]; // 1 element
        let positions = vector[0u8, 1u8]; // 2 elements -- mismatch
        verify_proof(root, leaf, proof, positions, SCHEME_SHA256);
    }

    #[test]
    #[expected_failure(abort_code = EInvalidPosition)]
    fun test_invalid_position_value() {
        let root = x"0000000000000000000000000000000000000000000000000000000000000000";
        let leaf = x"0000000000000000000000000000000000000000000000000000000000000000";
        let proof = vector[root];
        let positions = vector[2u8]; // invalid: must be 0 or 1
        verify_proof(root, leaf, proof, positions, SCHEME_SHA256);
    }

    // --- Cross-scheme isolation ---

    #[test]
    fun test_cross_scheme_proof_fails() {
        // Build tree with SHA256, try to verify with Blake2b
        let leaf0 = hash_leaf(b"alice", SCHEME_SHA256);
        let leaf1 = hash_leaf(b"bob", SCHEME_SHA256);
        let root_sha = hash_pair(leaf0, leaf1, SCHEME_SHA256);

        // Recompute leaf with Blake2b
        let leaf0_blake = hash_leaf(b"alice", SCHEME_BLAKE2B);
        let leaf1_blake = hash_leaf(b"bob", SCHEME_BLAKE2B);

        // Using SHA256 root but Blake2b leaf should fail
        let proof = vector[leaf1_blake];
        let positions = vector[0u8];
        assert!(!verify_proof(root_sha, leaf0_blake, proof, positions, SCHEME_BLAKE2B), 0);
    }
}
