[package]
name = "suicryptolib"
edition = "2024.beta"
published-at = "0x738433a8c905c57314cd2a9f8f4a2eb254cf45958d1694e9f0d9a7dc35a09490"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
suicryptolib = "0x0"

[dev-dependencies]

[dev-addresses]
