[package]
name = "suicryptolib"
edition = "2024.beta"
published-at = "0xd8ad089847187cbaa15da503e8892d5e3f0a2acd6cad1aff7be05bf0c127cf02"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
suicryptolib = "0x0"

[dev-dependencies]

[dev-addresses]
